name:                Plang
version:             1.0.0.0
github:              "Premwoik/Plang"
license:             BSD3
author:              "Przemysław Wojtasik"
maintainer:          "razussx@gmail.com"
copyright:           "2019 Przemysław Wojtasik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Premwoik/Plang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- text
- mtl
- containers
- hspec
- hspec-megaparsec
- cli
- directory
- process

library:
  source-dirs: src

executables:
  plang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Plang

tests:
  plang-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Plang
